name: "Sync PSE registration data"
on:
  schedule:
    - cron: '0 0 * * 1,3,5'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: "reinhart1010/psedb"
      - name: Fetch new data
        run: "go run main.go"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{secrets.GIT_AUTHOR}}
          author_email: ${{secrets.GIT_EMAIL}}
          message: "chore: (>_ ): data update ${{steps.timestamp.outputs.time}}"
